SELECT PARTITION_NAME,PARTITION_ORDINAL_POSITION, TABLE_ROWS, PARTITION_METHOD,round((DATA_LENGTH + index_length) / 1024 / 1024) "DB Size in MB" FROM information_schema.PARTITIONS WHERE TABLE_SCHEMA = 'zabbix' AND TABLE_NAME = 'history';

SELECT PARTITION_NAME,PARTITION_ORDINAL_POSITION, TABLE_ROWS, PARTITION_METHOD,round((DATA_LENGTH + index_length) / 1024 / 1024) "DB Size in MB" FROM information_schema.PARTITIONS WHERE TABLE_SCHEMA = 'zabbix' AND TABLE_NAME = 'history_uint';

SELECT PARTITION_NAME,PARTITION_ORDINAL_POSITION, TABLE_ROWS, PARTITION_METHOD,round((DATA_LENGTH + index_length) / 1024 / 1024) "DB Size in MB" FROM information_schema.PARTITIONS WHERE TABLE_SCHEMA = 'zabbix' AND TABLE_NAME = 'history_text';

SELECT PARTITION_NAME,PARTITION_ORDINAL_POSITION, TABLE_ROWS, PARTITION_METHOD,round((DATA_LENGTH + index_length) / 1024 / 1024) "DB Size in MB" FROM information_schema.PARTITIONS WHERE TABLE_SCHEMA = 'zabbix' AND TABLE_NAME = 'history_str';

SELECT PARTITION_NAME,PARTITION_ORDINAL_POSITION, TABLE_ROWS, PARTITION_METHOD,round((DATA_LENGTH + index_length) / 1024 / 1024) "DB Size in MB" FROM information_schema.PARTITIONS WHERE TABLE_SCHEMA = 'zabbix' AND TABLE_NAME = 'history_log';

